general {
    lock_cmd = pidof hyprlock || hyprlock       # what binary to run to lock
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after wake
}

# 1. Dim the screen (optional, helps battery)
listener {
    timeout = 150                                # 5 mins
    on-timeout = brightnessctl --save set 0%     # set monitor backlight to 0%
    on-resume = brightnessctl --restore          # restore backlight
}

# 2. Lock the screen
listener {
    timeout = 600                                # 10 mins
    on-timeout = brightnessctl --save set 0% && hyprlock                       # lock screen
    on-resume = brightnessctl --restore          # restore backlight
}

# # 3. Turn off screen (DPMS)
# listener {
#     timeout = 330                                # 5.5 mins
#     on-timeout = hyprctl dispatch dpms off       # command to turn off screen
#     on-resume = hyprctl dispatch dpms on         # command to turn on screen
# }
