listener {
    timeout = 90                                
    on-timeout = brightnessctl --save set 0%   
    on-resume = brightnessctl --restore       
}

listener {
    timeout = 300                            
    on-timeout = hyprlock                   
    on-resume = brightnessctl --restore    
}

listener {
    timeout = 600                               
    on-timeout = hyprctl dispatch dpms off     
    on-resume = hyprctl dispatch dpms on      
}
