# Change the directories to set wallpapers;:
preload = ~/Pictures/wallpapers/metropolis.png
preload = ~/Pictures/wallpapers/lake-tree-left.jpeg
preload = ~/Pictures/wallpapers/lake-tree-right.jpeg
preload = ~/Pictures/wallpapers/lcl-eva.jpg
preload = ~/Pictures/wallpapers/alien.jpg
preload = ~/Pictures/wallpapers/odyssey.jpg

# Make sure to also set the correct monitors (hyprctl mon:witors)
# wallpaper = eDP-1,~/Pictures/wallpapers/metropolis.png
# wallpaper = DP-4,~/Pictures/wallpapers/metropolis.png
# wallpaper = eDP-1,~/Pictures/wallpapers/metropolis.png
# wallpaper = ,~/Pictures/wallpapers/metropolis.png

wallpaper = eDP-1,~/Pictures/wallpapers/odyssey.jpg
wallpaper = ,~/Pictures/wallpapers/odyssey.jpg
